version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
    - 8000:8000
    volumes:
    - .:/app
    depends_on:
      - db
      - redis
#    network_mode: "host"
    extra_hosts:
      -  "docker.host: 192.168.49.1"

#  rabbitmq:
#    image: rabbitmq:3.7.8
#  db:
#    image: mysql:5.7.22
#    command: ['--max_allowed_packet=2G','--memory-swappiness=1 --memory=2G ']
#    restart: always
#    environment:
#      MYSQL_DATABASE: mysql
#      MYSQL_USER: soumya
#      MYSQL_PASSWORD: soumya
#      MYSQL_ROOT_PASSWORD: soumya
#    volumes:
#    - .dbdata:/var/lib/mysql
#    ports:
#    - 33066:3306

  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: soumya
      POSTGRES_USER: soumya
      POSTGRES_PASSWORD: soumya
      PGDATA: /var/lib/postgresql/data
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: soumyarout80@gmail.com
      PGADMIN_DEFAULT_PASSWORD: soumya
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
    - "db:pgsql-server"

# docker run --rm -it --hostname my-rabbit -p 15672:15672 -p 5672:5672 rabbitmq:3-management

  celery:
    build: .
    command: celery -A k8s_notification worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-worker:
    build: .
    command: celery -A k8s_notification worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A k8s_notification beat -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis



  redis:
    image: "redis:alpine"

volumes:
  db-data:
  pgadmin-data: