# Generated by Django 3.1.3 on 2021-01-11 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_account', models.CharField(max_length=200)),
                ('cluster_name', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('slack_channel', models.CharField(default='NA', max_length=200)),
                ('notification_state', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Enable', max_length=7)),
                ('k8s_endpoint', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_account', models.CharField(max_length=200)),
                ('cluster_name', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=200)),
                ('metrics', models.CharField(max_length=200)),
                ('resource_type', models.CharField(max_length=200)),
                ('resource_name', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default=False, max_length=5)),
                ('status_message', models.CharField(max_length=500)),
                ('notification_state', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Enable', max_length=7)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.account')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_account', models.CharField(max_length=200)),
                ('cluster_name', models.CharField(max_length=200)),
                ('metrics', models.CharField(max_length=200)),
                ('resource_type', models.CharField(max_length=200)),
                ('resource_name', models.CharField(max_length=200)),
                ('alert_status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default=False, max_length=5)),
                ('limit', models.IntegerField(default=5)),
                ('last_sent', models.DateTimeField()),
                ('next_schedule', models.DateTimeField(default=datetime.datetime(2021, 1, 11, 20, 14, 5, 287946, tzinfo=utc))),
                ('count', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.account')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
        ),
    ]
