# Generated by Django 3.1.3 on 2021-01-12 03:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20210112_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='next_schedule',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 3, 44, 21, 197303, tzinfo=utc)),
        ),
    ]
