# Generated by Django 3.1.3 on 2021-01-12 04:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20210112_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='next_schedule',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 4, 51, 10, 201353, tzinfo=utc)),
        ),
    ]
