# Generated by Django 3.1.3 on 2021-01-17 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20210112_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name_plural': 'resources'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='next_schedule',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 19, 21, 15, 456153, tzinfo=utc)),
        ),
    ]
